### ISSUE TITLE
download the dataset

### ISSUE THREAD

**Issue by cploveflower** [D-X-Y/SAN#20]
Hello@D-X-Y:
I  am very grateful for your contribution，but when I download the dataset ,
it always has some problems,like the download speed is low and I have a failure,
I think the best way is that I need to use ps to make the dataset by myself, 
can you tell me how to make it use ps at detail or you have any other solution about it?
Thank you very much!

**Comment by D-X-Y** [comment]
Thanks for your interest. Since this work is done almost two years ago, I can not find the detailed hyper-parameters used for generating these images. I'm splitting tgz files into several small files, and hope it would be easier to download multiple small files instead of a large tgz file. I will let you know when I finish this procedure (should be done in hours).

**Comment by cploveflower** [comment]
it's very kind of you to do this for me,thank you very much!

**Comment by D-X-Y** [comment]
I just upload those splits to Google Driver. Please find the link at https://github.com/D-X-Y/SAN#datasets-download.

**Comment by cploveflower** [comment]
Thank you for your help,I have downloaded it successfully

**Comment by D-X-Y** [comment]
You are welcome~
