### ISSUE TITLE
Could you please share PS generation code?

### ISSUE THREAD

**Issue by weishy-xun** [D-X-Y/SAN#7]
I want to generate datasets from the original dataset. Your paper said that the datasets are PS-generated. Can you share the filters or code you use in photoshop? Thank you

**Comment by D-X-Y** [comment]
Hi xun, sorry about that. I lost the PS template for these styles >.<. You may try some similar transformations in PS.

**Comment by weishy-xun** [comment]
Is there a guideline for the transformations? 
As I can see, gray-style is just gray, sketch-style looks like brighter gray, and light-style looks very yellow. 
Have you tried other styles? I wonder if the four styles you use is selected. Or maybe you just try something and it works very well so you think similar transformation will be useful too.

**Comment by D-X-Y** [comment]
Hi, the light-style is similar to the 'classical' style in many software, such as meituPic https://mt.meipai.com/en/. If you look into the details of the sketch-style, you will find the strip texture, which is included in the gray-style.
I try about 10 styles by manually using meituPic software to edit images and check whether the detector predicts the same location on different styles. Unfortunately, the predictions are different for different styles.  I pick up 3 of them, because these three styles can be easily applied on thousands of images by PhotoShop, however other styles are not (meituPic cannot apply a style on batch images and one have to edit one by one, which costs much time).

**Comment by weishy-xun** [comment]
Thank you.
